bug: "unresolved call" error should not be reported, whereas it is when a dynamically-dispatched method has a param argument

See also generic-method-with-param-arg-2.future.

This test is a variation on generic-method-with-param-arg-2.chpl
whereby the call _arrAlias.getAllocationDomainForDefaultRectangularArray(3)
is wrapped in an additional proc xxx().

Currently I get:

test/classes/vass/generic-method-with-param-arg-3.chpl:21: In function 'getAllocationDomainForDefaultRectangularArray':
test/classes/vass/generic-method-with-param-arg-3.chpl:24: error: unresolved call 'xxx(BaseArr)' [functionResolution.cpp:1598]

When compiling with --explain-call xxx, the following line is shown twice:

  generic-method-with-param-arg-3.chpl:24: note: call: xxx(BaseArr)

Just like with generic-method-with-param-arg-2.chpl, the first time
it finds visible functions and resolves it twice, the second time it doesn't.
